### ISSUE TITLE
How to use with Flash Memory in ESP8266?

### ISSUE THREAD

**Issue by Louis469** [AlirezaSalehy/WAVRecorder#5]
How can I use the WAVRecorder without an SD card and with the flash memory that comes with the esp8266?

**Comment by A-R-S-D** [comment]
Hi! Thanks for reaching out. Actually, i remember that I've tried to do so but i don't remember why i ended up with SD card. I don't think that there was an implementation problem because SD card FS, LittleFS and SPIFFS inherit from the same interface and implement the same API. 

But there may be some practical performance concerns, note that ESP8266 uses the flash to fetch program instructions, too. So, the whole bandwidth won't be allocated to audio data storage.  If you are trying to record human speech then based on its spectrum and Nyquist's rule you have data generation rate of at least 4kHz. Assuming data units to be of size 2 bytes, we have 8KB of data that needs to be stored. So, if you have a real-time application, you need to have writing speed even more than 8KB/s because there is also ADC sampling that needs to be considered. Because Arduino implementation does not support higher utilization of hardware and ESP8266 hardware does not offer many features as well. (Like all the crazy stuff that architecture of STM32 MCUs offer.)

**Comment by Alireza99Salehi** [comment]
Hi! Thanks for reaching out. Actually, i remember that I've tried to do so but i don't remember why i ended up with SD card. I don't think that there was an implementation problem because SD card FS, LittleFS and SPIFFS inherit from the same interface and implement the same API.  (And as you may know LittleFS is preferred over SPIFFS)

But there may be some practical performance concerns, note that ESP8266 uses the flash to fetch program instructions, too. So, the whole bandwidth won't be allocated to audio data storage.  If you are trying to record human speech then based on its spectrum and Nyquist's rule you have data sampling rate of at least 4kHz. Assuming sampled data units to be of size 2 bytes, we have 8KB of data that needs to be stored each second. So, if you have a real-time application, you need to have writing speed even more than 8KB/s because there is also ADC sampling that must be considered. And it is sequential because Arduino implementation does not support higher utilization of hardware (At least at that time) and the ESP8266 hardware does not offer many features as well. (Like all cool stuffs architecture of STM32 MCUs offer)

**Comment by Alireza99Salehi** [comment]
Since there is no more discussion i suppose the question is answered, and i close the issue. If there is more to be helped with, please let me know.

**Comment by A-R-S-D** [comment]
Since there is no more discussion i suppose the question is answered, and i close the issue. If there is more to be help with, please let me know.

**Comment by Louis469** [comment]
Sorry to be a bit needy, but can you please give some example code if possible?

**Comment by Alireza99Salehi** [comment]
Yes, i can, but i can't give a fully debugged code because i have no access to the required tools.  In the example code at root of repository, you should replace `SD.begin` with `SPIFFS.begin` or `LittleFS.begin` and instead of `SD.exists`, `SD.remove` and `SD.open` you should use SPIFFS's (or LittleFS) `exists`, `remove` and `open` methods. 

Hope this helps!
A-R-S-D
